action_id: trunk-share-with-everyone
date: 2024-07-28 17:32:59
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1722187979
full_timestamp:
  nanos: 748204000
  seconds: 1722187979
trunk_version: 1.22.2
